### PR TITLE
Fixes for sub-cycle rendering (Issue #244)

### PR DESCRIPTION
**Pull request by Ganesh-AT**
Modified rendering of sub-cycles (including gaps in subcycles) to handle
(a) wave strings starting with sub-cycles
(b) wave strings with back-to-back sub-cycles
(c) sub-cycles starting with dots or vertical markers, and dots following sub-cycles

This commit resolves rendering issues reported in #244

### CODE REVIEW

**Comment by Ganesh-AT** [comment]
I also have another commit related to the above PR (to fix sub-cycles beginning with a gap) here: https://github.com/wavedrom/wavedrom/commit/6312c028293afb6d96b925a26f46ba946a98e149

I will push that in if / when this PR gets accepted.

**Comment by drom** [comment]
Please add test for these change.

**Comment by Ganesh-AT** [comment]
> 
> 
> Please add a test for this change.

Do you mean an updated 'test.html' with new examples?  [ test/test.html ] This is my first PR, and I am not sure what you mean by 'adding a test' other than all the examples I have cited in my replies in #244

**Comment by Ganesh-AT** [comment]
test-sub-cycles.html which had some of the old test vectors has now been updated with some of the newer ones in #244 cc @drom - Please let me know if there is anything else to be added as a test for this change.

**Comment by Ganesh-AT** [comment]
After additional testing / real-world use with my fork, I found an issue related to back-to-back sub-cycles with gaps inside them. Additionally, I had to add support for sub-cycles in the node member also - enabling the arc end-points / markers to track the corresponding sub-cycles in the wave member. 

Changes for the above, as well as an additional test for the new feature in test-sub-cycles.html are in the three commits above. cc @drom

**Pull request closed without merging**
