### PR TITLE
Add new syntax "1(5)" to say how much a signal should repeat

### PR DESCRIPTION
**Pull request by adrienkohlbecker**
Hello,

Using `.` to repeat signals works great, but I often have to count dots to see how much my signals are repeating. So to make this more explicit and make complex diagrams easier to manage, I would like to propose a new syntax, which explicitly supports specifying the number of repeats for a signal:

```bash
# with dots
"1.........."
# with new syntax
"1(10)"
```

Here is what the new test case looks like:

Screenshot 2021-09-30 at 22 05 01

@drom I hope this is interesting to you. Let me know if you have any questions or suggestions.

### CODE REVIEW

**Comment by drom** [comment]
Hi @adrienkohlbecker thank you for Interesting Idea.
It might make sense to repeat any character not only `.`
for example:

```
0=(5)0 --> 0=====0
p(5)   --> ppppp
1.(5)  --> 1.....
```

Extending your idea to repeating arbitrary sequences:

```
0(= 5)0 --> 0=====0
(p 5)   --> ppppp
1(. 5)  --> 1.....
(=.. 5) --> =..=..=..=..=..
```

Also we should then allow recursive definitions:

```
0((1. 3)0 2)1 --> 01.1.1.01.1.1.01
```

**Comment by adrienkohlbecker** [comment]
@drom interesting ideas!

My use case is I'm building a diagram out of signals with defined propagation delays. The goal of this PR was to be able to say in the code how much the delay is. In your `1.(5)  --> 1.....` example, the signal actually repeats 6 times while the code says 5, so there is additional mental load, you need to remember to add one in your head. This is why I went with building an extension of `.` rather than a generic loop syntax. 

This is my current WIP diagram (includes some stuff from other PRs):
Screenshot 2021-10-03 at 13 58 08

The way I'm defining the CPU read signal for example is: `wave: '6..(10)x(23)7(27)x(30)6(10)..'`. As you can see, I'm able to put the propagation delays for my signal directly in the code.

Hopefully that provides some context!

**Comment by drom** [comment]
Hi @adrienkohlbecker 
I see more context now. Could you file Feature request (in issues) separate from this PR, explain you rationale.
This feature touches wide scope, and needs a broader discussion.

**Comment by Ganesh-AT** [comment]
Was a feature request ever filed for this PR? In the absence of that, I am taking the liberty to discuss this feature in this thread.

@drom Would you be introducing this repeat() scheme as part of mainline WaveDrom in the future?

I am trying to integrate some of the changes in the custom fork of @adrienkohlbecker  into my version (**while also wanting to ensure full compatibility with mainline WaveDrom**). While some of the new features in Adrien's fork (like the replacement of inline styles with classes) are simply the right thing to do, I am not entirely convinced for the need of this feature. While reducing the amount of code that the user needs to type is a big plus point, the fact that the numbers enclosed within the parenthesis could represent bricks themselves (so, the reader needs to be careful while interpreting them, based on the context) leaves me a bit ambivalent. If I understand the feature right:

```
wave: '6..(10)x(23)7(27)x(30)6(10)..'
```

is the same as:

```
wave: '6.' + '.'.repeat(10)
    + 'x'.repeat(23)
    + '7'.repeat(27)
    + 'x'.repeat(30)
    + '6'.repeat(10) + '..'
```

This allows the specification of the propagation delays to be embedded in the wave string at the cost of a little verbosity, but much increased readability.

In addition, I think these types of modifications to the core WaveJSON grammar can be better handled by the 'plugin wrapper' scheme that we were discussing in another [thread](https://github.com/wavedrom/wavedrom/issues/335#issuecomment-1791348684). The signal members with parentheses in the wave / node string can be intercepted and modified as above before being put into the final object parsed by the WaveDrom engine. 

So, overall, I am not as keen on getting this into the mainline as some of the other PRs like #390. However, if you think this will make it into the mainline, I will work on integrating support for the new syntax into my fork also.

**Comment by adrienkohlbecker** [comment]
Someone posted above then deleted their message, so I thought I would give an update.

I'm now moving away from this idea. At a higher level, I think wavedrom's syntax makes working on large and/or frequently modified diagrams difficult to do for humans: we're not good at deriving meaning from a list of repeating characters. I still think the rendered diagrams look good, and so I'm now working on a DSL library for generating wavedrom syntax in a programmatic way. It is a WIP and I'm not ready to share code yet, but in a nutshell, a human can write numbers, and the library repeats the necessary characters as needed.

I will be closing this PR, but if someone wants to take over this idea, feel free.

**Comment by Ganesh-AT** [comment]
Thanks for the additional information.

I had deleted my response in this thread, as I discovered some invalid points in some of the objections that I had raised. Additionally, while trying to integrate the 'repeat' updates from your fork into my current version, I discovered it was not simple (As the changes conflicted with some of the sub-cycle bug fixes in my fork). I had actually wanted to finish up that integration before contributing again in this thread. However, with the PR being dropped, it saves me some effort :)

**Pull request closed without merging**
