### PR TITLE
Add narrower skins

### PR DESCRIPTION
**Pull request by adrienkohlbecker**
I recently needed to increase the horizontal resolution of my diagrams. One example is a diagram with 100 horizontal points, each representing a nanosecond, depicting signal propagation in a computer circuit, which I've attached below.

Unfortunately, even the `narrow` theme is quite wide for this use case. So, I went to my SVG editor and created two new themes, by individually scaling down each element by 2 and 4 horizontally. For lack of a better naming scheme, I'm naming these `narrower` and `narrowerer`, but I'm open to suggestions!

I hope that these can be useful to someone else!

Here is an example of a diagram I'm working on with each skin (note that these screenshots include other patches I haven't submitted yet):

## `narrow` (doesn't fit the screen)

Screenshot 2023-08-01 at 22 14 10

## `narrower`

Screenshot 2023-08-01 at 22 14 31

## `narrowerer`

Screenshot 2023-08-01 at 22 14 48

### CODE REVIEW

**Comment by adrienkohlbecker** [comment]
`eslint` is failing for code unrelated to this PR, I fixed it in #390

**Comment by adrienkohlbecker** [comment]
I also have more examples of the `narrowerer` skin with 250 horizontal points in my project repo here https://github.com/adrienkohlbecker/BB816#timing-diagrams

**Comment by drom** [comment]
LGTM

**Comment by Ganesh-AT** [comment]
Can we rename the 'narrowerer' skin to 'narrowest'? or adopt : 'narrow', 'narrow_s', and 'narrow_xs' ? (and, if someone wants to create an even more compressed skin, it can be narrow_xxs)?

**Comment by Ganesh-AT** [comment]
Having worked on multiple new features for our in-house use of this tool over the last four years, I would like to provide my two cents about this PR, even though it has already been merged. One of the things I realized recently is that I had been adding multiple small features over the last several years to the code base when they could have been handled generically using a single new feature.

At the risk of digressing a little, I would like to recount my experience with a couple of in-house feature requests: Enabling coloring of certain segments of a wave lane, and ability to change the line style of signals (from straight to dashed, to denote a delayed version that could then be overlaid on the same signal - like the picture in this [post](https://github.com/wavedrom/wavedrom/issues/121#issuecomment-541269215) in #121). Not surprisingly, one of the currently outstanding PRs - #271 - deals with that topic. @wmin0 has taken a lot of trouble to modify the grammar to implement just this feature alone. Initially, I was tempted to just port in that PR into my custom fork and even had that version ready when the second request came in. After some deliberations, I realized that offering an 'overrideSkinStyle' feature for each signal lane would be a much more flexible solution that could address the two requirements and also much more.

Anyways, coming back to this particular problem being solved with new skins, I was wondering if offering a config field, say, brickScale, could be a more flexible solution. (**Edit: In fact, we don't even need a new config field. If we relax the constraint that hscale has to be a non-zero positive integer, and allow it to take values between (0,1), it can serve the same purpose**).

As a quick test, I inspected one of the SVGs being rendered by WaveDrom and added a 'scale(0.5 1)' to one of the transform attributes under 'use'. Adding it to the ```<g id="wavelane_draw_?_?">``` with a new transform spec compressed the whole lane, but also compressed the data labels. Arc paths could also be scaled similarly, but again the text labels got squished and needed rescaling with a 'scale(2 1)'. This didn't work with data labels, though (Edit: Need to move the x,y from the text element to a new transparent rect wrapper, and use the de-scale factor on the text alone). So, that would need a bit of handling in the code base.

Ordinarily, if the custom fork from @adrienkohlbecker had only included the new skins and nothing else, I would not have bothered with outlining the above alternative. But, I see there is plenty of customization in the fork - so, being clearly very familiar with the code base, I was wondering if he would be interested in adding the brickScale feature as a more flexible alternative / complement to this PR.

**Pull request merged**
