### PR TITLE
Add new edge with tee termination

### PR DESCRIPTION
**Pull request by adrienkohlbecker**
Hello,

This MR adds a new `tee` edge termination. This is what it looks like:

Screenshot 2021-10-03 at 13 32 06

Note that it only works with hidden (capitalized) nodes, since the node label is displayed above the termination. It makes sense for the tee to be displayed exactly at the point where a signal transitions

Related issues https://github.com/wavedrom/wavedrom/issues/205 https://github.com/wavedrom/wavedrom/issues/328

@drom hope you find this interesting! Let me know if you have any questions or suggestions.

### CODE REVIEW

**Comment by drom** [comment]
@adrienkohlbecker Please clean `eslint` issues

**Comment by adrienkohlbecker** [comment]
@drom all good!

**Comment by drom** [comment]
I have published v2.8.2 with this change, and pushed to editor, tutorial on website

**Comment by drom** [comment]
@adrienkohlbecker would you update tutorial too?

**Comment by adrienkohlbecker** [comment]
@drom already on it :-) https://github.com/wavedrom/wavedrom.github.io/pull/76

**Pull request merged**
